/**
 * Persistent, unmissable banner shown whenever the active adapter reports
 * simulation_mode. Never make Mock mode look like a real node --
 * docs/architecture.md principle 6.
 */
export function SimulationBanner() {
  return (
    <div className="sim-banner" role="status">
      ⚠ SIMULATION MODE — this data is generated by the Mock adapter, not a real QRX node
    </div>
  );
}
